dubbo:
  application:
    name: center-web
  registry:
    address: 192.168.230.128:2181
    protocol: zookeeper

server:
  port: 80
fdfs:
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.230.128:22122
  so-timeout: 1500

#上传文件的大小限制
spring:
  rabbitmq:
    virtual-host: /java
    username: user
    password: 111047
    addresses: 192.168.230.128
  servlet:
    multipart:
      max-file-size: 10MB


#图片的服务器
images:
  server: http://192.168.230.128/